### PR TITLE
replaces for loops by spire's cfor in linalg functions

### PR DESCRIPTION
**Pull request by nikdon**
This PR replaces for loops by spire's cfor for ```breeze.linalg``` functions and therefore increases performance of them.

### CODE REVIEW

**Comment by dlwh** [comment]
thanks for doing this! any chance I could get you to use cforRange where possible? It's much clearer most of the time.

**Comment by dlwh** [comment]
(fwiw, i bet most of these wouldn't be noticeable performance wise since they're not the inner loop)

**Comment by dlwh** [comment]
note there's also cforRange2

**Comment by nikdon** [comment]
Hi, David. I've replaced cfor by cforRanges where it was possible. Gains are not significant, but.. :) After CI tests I'm going to rebase it if you are ok with these proposals for PR

**Comment by dlwh** [comment]
looks good.

**Comment by dlwh** [comment]
awesome, thanks!

**Pull request merged**
