### PR TITLE
Upgrade latest cross Scala version from 2.12.1 to 2.12.8. Upgrade SBT version from 1.1.0 to 1.2.8 #744

### PR DESCRIPTION
**Pull request by helena**
https://github.com/scalanlp/breeze/issues/744

### CODE REVIEW

**Comment by helena** [comment]
Hoping for a new release with the version upgrades ;)

**Comment by helena** [comment]
I have to fix the target - CI break.

**Comment by dlwh** [comment]
some of the CI's on me. I merged a change that breaks 2.11 a while back.

**Comment by helena** [comment]
@dlwh NP, I  noticed that. I wanted to run with openJdk 11 with java.version in the build but I'll do that in a separate PR, which is better to do anyway, unless someone beats me to it :-)

**Comment by dlwh** [comment]
I went ahead and just removed 2.10 from Travis, and I think everything's building fine now, modulo the usual flakiness with floating point + scalacheck (still haven't managed to totally stamp it out)

**Comment by dlwh** [comment]
thanks, and sorry for being slow!

**Comment by helena** [comment]
Thanks @dlwh 👍

**Pull request merged**
