### PR TITLE
Basic Runge-Kutta ODE solver

### PR DESCRIPTION
**Pull request by jaketimothy**
This is an initial implementation of an ODE solver, following issue #478.

For more ideas, see [scipy's odeint](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.integrate.odeint.html) and [matlab's odeset](http://www.mathworks.com/help/matlab/ref/odeset.html).

### CODE REVIEW

**Comment by dlwh** [comment]
Cool, thanks!

Could you add just a bit more documentation/links? Mostly I didn't understand the array of t's until I read the matlab documentation you linked. (I don't really know ODEs.) Basically I just want a sentence or two that explains what each of the parameters does.

Also, it's not clear to me why you sometimes use Array[Double] and sometimes use DenseVector[Double].

**Comment by jaketimothy** [comment]
Oh, of course!

The use of Array is something I would appreciate some input on.  DenseVector[Double] is used to hold any state vector.  The derivatives function f and the initial value y0 use DenseVector[Double].  This way, users can leverage breeze.linalg when creating the derivatives function f.  Currently, the solver uses Array as the larger container, mapping t: Array[Double] to the result: Array[DenseVector[Double]].  Thoughts?  

Now, for the error tolerance input values, I chose Array[Double] to use the convenient Array.empty and Array.isEmpty.  I would like to make them DenseVector[Double], but I'm not sure how best to implement optional DenseVector parameters.

**Comment by dlwh** [comment]
ok cool! Could you add something along those lines to the comments?

I think it makes sense to do arrays like you said, in that case.

**Comment by dlwh** [comment]
thanks!

**Pull request merged**
